
name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Ruff
      uses: astral-sh/ruff-action@v3
      with:
        version-file: "pyproject.toml"
        
    - name: Ruff check
      uses: astral-sh/ruff-action@v3
      with:
        args: "format --check"
  
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --all-extras --dev
    
    - name: Run tests
      run: uv run pytest tests

    - name: Run mypy
      run: uv run mypy .
